name: weather_clean
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  dartz: ^0.10.1
  http: ^1.1.2
  dio: ^5.4.0
  get_it: ^7.6.4
  geolocator: ^10.1.0
  liquid_pull_to_refresh: ^3.0.1
  json_annotation: ^4.8.1
  injectable: ^2.3.2
  internet_connection_checker_plus: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  flutter_lints: ^3.0.1




flutter:

  assets:
    - images/

  uses-material-design: true
